include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  language:
    strict-casts: true

linter:
  rules:
    - combinators_ordering
    - comment_references
    - directives_ordering
    - test_types_in_equals
    - throw_in_finally
