// Mocks generated by Mockito 5.0.6 from annotations
// in mockito/example/iss/iss_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:math' as _i3;

import 'package:http/src/client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'iss.dart' as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeClient extends _i1.Fake implements _i2.Client {}

class _FakePoint<T extends num> extends _i1.Fake implements _i3.Point<T> {}

/// A class which mocks [IssLocator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIssLocator extends _i1.Mock implements _i4.IssLocator {
  MockIssLocator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient()) as _i2.Client);
  @override
  _i3.Point<double> get currentPosition =>
      (super.noSuchMethod(Invocation.getter(#currentPosition),
          returnValue: _FakePoint<double>()) as _i3.Point<double>);
  @override
  _i5.Future<void> update() =>
      (super.noSuchMethod(Invocation.method(#update, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
}
